[package]
name = "GNMX"
version = "0.1.0"
authors = ["thomas <thomas@dooms.eu>", "ward <wgauderis@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
